name: CI with Python setup for Application

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m venv venv 
          source venv/bin/activate 
          pip install --upgrade pip  
          pip install -r requirements.txt  

      - name: Run tests
        run: |
          source venv/bin/activate 
          pytest  

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: Package
          path: build  
