name: CI with Python setup for Application

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate  # Activate virtual environment
          pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          source venv/bin/activate  # Activate virtual environment again if not already active
          pytest  # Run pytest to execute tests

      # This step is for uploading artifacts, but make sure you have something in 'build'
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: Package
          path: build  # Ensure 'build' directory exists and contains something to upload
